-- Sample content from the prototype. Run AFTER schema.sql.
-- Safe to re-run: it clears these tables first.

truncate public.feed, public.coaches, public.squads, public.volunteer_roles, public.news_defaults restart identity;

insert into public.feed (type, title, start_date, end_date, host, league, level, license, pool_type, venue, closing, status, entry_url, officials_url, volunteer_url, results_url, league_url, conditions_url, conditions_label, entry_file_url, entry_file_label, current_entries_url, notes, blurb, link, color, tag, note, img) values
  ('meet', 'BPSC End of Season SC L3 Meet', '2026-07-11', '2026-07-12', null, null, 'Level 3', '3ER261281', '25m Short Course', 'Basildon Sporting Village', null, 'open', 'http://www.galaorganiser.co.uk/entry/meetentry.php?Meet=BASTEO26', 'https://swim-meet.com/Availability/?m=9133', null, null, null, '#', '2026 BPSC End of Season SC Meet L3 – Conditions', '#', 'EO26_EntryData', 'https://www.galaorganiser.co.uk/entry/meet_entries.php?Meet=BASTEO26', 'Officials wanted — please declare your availability.', null, null, null, null, null, null),
  ('meet', 'BPSC Season Opener SC L3', '2026-09-12', '2026-09-13', null, null, 'Level 3', null, '25m Short Course', 'Basildon Sporting Village', null, 'open', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('meet', 'BPSC 800m Distance Qualifier', '2026-10-10', null, null, null, 'Club', null, null, 'Basildon Sporting Village', null, 'open', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('meet', 'BPSC Autumn Qualifier', '2026-10-31', '2026-11-01', null, null, 'Club', null, null, 'Basildon Sporting Village', null, 'open', null, null, null, null, null, null, null, null, null, null, 'Volunteers needed — see the Volunteering page!', null, null, null, null, null, null),
  ('meet', 'BPSC 1500m Distance Qualifier', '2026-11-14', null, null, null, 'Club', null, null, 'Basildon Sporting Village', null, 'open', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('meet', 'BPSC Last Chance County Qualifier', '2026-11-28', '2026-11-29', null, null, 'Club', null, null, 'Basildon Sporting Village', null, 'open', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('external_meet', 'London Legacy Open Meet', '2026-12-05', '2026-12-06', 'London Aquatics Centre', null, 'Level 3', null, '50m Long Course', 'London Aquatics Centre, Stratford', null, 'open', null, null, null, null, null, null, null, null, null, null, 'Club entries are submitted by the Open Meets Secretary — check the meet conditions for qualifying times.', null, null, null, null, null, null),
  ('external_meet', 'Essex County Championships', '2027-01-23', '2027-01-31', 'Essex County ASA', null, 'Level 2', null, '25m Short Course', 'Venue TBC', null, 'closed', null, null, null, null, null, null, null, null, null, null, 'County qualifying times apply.', null, null, null, null, null, null),
  ('team_meet', 'Arena League — Round 1', '2026-10-17', null, null, 'Arena League', null, null, '25m Short Course', 'Venue TBC', null, null, null, null, null, null, null, null, null, null, null, null, 'Team selected by the coaches — selected swimmers will be contacted directly with arrival times.', null, null, null, null, null, null),
  ('team_meet', 'Essex League — Round 1', '2026-11-07', null, null, 'Essex League', null, null, '25m Short Course', 'Venue TBC', null, null, null, null, null, null, null, null, null, null, null, null, 'Team selected by the coaches.', null, null, null, null, null, null),
  ('social', 'Summer BBQ & Fun Gala', '2026-08-15', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Family fun gala followed by the annual BBQ on the field. Bring the whole family — inflatables race included.', '#', 'linear-gradient(135deg,#f26b21,#ffb25e)', null, null, null),
  ('social', 'Quiz Night Fundraiser', '2026-09-25', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Teams of six, bar open, proceeds towards new club timing equipment. Book your table early!', '#', 'linear-gradient(135deg,#101014,#3c3c46)', null, null, null),
  ('social', 'Presentation Evening', '2026-09-04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Celebrating the season — trophies, awards and the famous coaches'' review of the year.', '#', 'linear-gradient(135deg,#d4551a,#101014)', null, null, null),
  ('news', 'Club Championships wrap-up', '2026-05-18', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Results, personal bests and a huge thank you to the volunteers who made the weekend happen.', null, null, 'Racing', null, null),
  ('news', 'New Academy intake open', '2026-07-01', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Spaces opening in our Academy squads for swimmers moving up from lessons — see Join Us for details.', null, null, 'Club', null, null),
  ('news', 'Swim Camp 2026 — Lanzarote', '2026-08-20', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Places open for our warm-weather training camp at Club La Santa — intensive poolside sessions for squads moving up in level.', null, null, 'Trips', null, 'images/WS-Spain-lanzarote-Costa-Teguise-03-Sports-Abroad.jpg'),
  ('news', 'Summer Nationals', '2026-07-28', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Good luck to our qualified swimmers racing at Ponds Forge this summer — the whole club will be behind you.', null, null, 'Racing', null, 'images/Ponds_Forge_Summer_Meet_2024_branding_1200x675.avif'),
  ('news', 'Timekeepers course', '2026-08-05', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A free Swim England Timekeeping course is running next month — no experience needed, and it''s the easiest way to start volunteering poolside.', null, null, 'Volunteering', null, 'images/Timekeepers-course.webp'),
  ('training', 'No Friday training — pool maintenance', '2026-07-24', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Basildon Sporting Village pool closed for planned maintenance. All squads unaffected on other training days.', null),
  ('training', 'Half-term altered times', '2026-10-26', '2026-10-30', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Squad times shift earlier during half-term week — check the noticeboard for your squad''s slot.', null);

insert into public.coaches (name, role, quals, squads, photo, sort_order) values
  ('Doug Campbell', 'Head Coach', 'Swim England Senior Coach · DBS · Safeguarding & first aid', '["Performance","National/Regional prep"]'::jsonb, 'images/coaches/Capture.JPG', 0),
  ('Priya Shah', 'Development Coach', 'Swim England Coach (Level 2) · DBS · Safeguarding', '["Development","County prep"]'::jsonb, null, 1),
  ('Jamie Round', 'Youth & Sprint Coach', 'Swim England Coach (Level 2) · DBS · Safeguarding', '["Youth Sprint","Transition"]'::jsonb, null, 2),
  ('Ella Moore', 'Academy Lead', 'Swim England Assistant Coach · DBS · Safeguarding', '["Academy — Green to Red hats"]'::jsonb, null, 3);

insert into public.squads (name, lead, sessions, sort_order) values
  ('Gold 1', 'Doug C', '[{"day":"Mon","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Mon","start":"19:30","end":"20:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"18:30","end":"20:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Wed","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"18:15","end":"19:15","loc":"BSV Meeting Room","type":"land"},{"day":"Thu","start":"19:15","end":"21:00","loc":"BSV Long Course","type":"pool"},{"day":"Fri","start":"18:00","end":"19:30","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"06:00","end":"07:45","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"16:15","end":"18:15","loc":"BSV Long Course","type":"pool"}]'::jsonb, 0),
  ('Gold 2', 'Doug C', '[{"day":"Mon","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Mon","start":"18:30","end":"19:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"05:30","end":"07:00","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"18:15","end":"19:15","loc":"BSV Meeting Room","type":"land"},{"day":"Thu","start":"19:15","end":"21:00","loc":"BSV Long Course","type":"pool"},{"day":"Fri","start":"18:00","end":"19:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"06:00","end":"07:45","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"16:15","end":"18:15","loc":"BSV Long Course","type":"pool"}]'::jsonb, 1),
  ('Gold 3', 'Steph S', '[{"day":"Mon","start":"17:30","end":"18:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Wed","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Wed","start":"19:00","end":"20:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"17:15","end":"18:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Fri","start":"19:30","end":"20:30","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"06:45","end":"07:30","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"16:15","end":"18:15","loc":"BSV Long Course","type":"pool"}]'::jsonb, 2),
  ('Silver 1', 'Chris S', '[{"day":"Mon","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Mon","start":"20:30","end":"21:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Wed","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Thu","start":"18:15","end":"19:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"20:30","end":"21:30","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"06:00","end":"07:45","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Meeting Room","type":"land"}]'::jsonb, 3),
  ('Silver 2', 'TBC', '[{"day":"Tue","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Wed","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"17:15","end":"18:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Fri","start":"20:30","end":"21:30","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sun","start":"06:45","end":"07:30","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Short Course – Shallow End","type":"pool"}]'::jsonb, 4),
  ('Silver 3', 'TBC', '[{"day":"Tue","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"17:30","end":"18:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"17:15","end":"18:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"06:45","end":"07:30","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Short Course – Shallow End","type":"pool"}]'::jsonb, 5),
  ('Bronze', 'TBC', '[{"day":"Mon","start":"20:30","end":"21:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Thu","start":"17:15","end":"18:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"19:00","end":"20:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"06:45","end":"07:30","loc":"BSV Meeting Room","type":"land"}]'::jsonb, 6),
  ('Junior Pathway', 'Nigel B', '[{"day":"Mon","start":"19:30","end":"20:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Tue","start":"05:30","end":"07:00","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Tue","start":"20:15","end":"21:15","loc":"Billericay Pool","type":"pool"},{"day":"Thu","start":"05:30","end":"07:00","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Thu","start":"17:15","end":"18:15","loc":"BSV Meeting Room","type":"land"},{"day":"Fri","start":"19:00","end":"20:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"06:00","end":"07:45","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sun","start":"06:45","end":"07:30","loc":"BSV Meeting Room","type":"land"},{"day":"Sun","start":"07:45","end":"08:45","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 7),
  ('Red Hats', 'Chris S', '[{"day":"Wed","start":"18:00","end":"19:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Fri","start":"19:30","end":"20:30","loc":"BSV Short Course – Shallow End","type":"pool"},{"day":"Sat","start":"15:00","end":"16:00","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 8),
  ('Blue Hats', 'TBC', '[{"day":"Wed","start":"17:00","end":"18:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Sat","start":"15:00","end":"16:00","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 9),
  ('Yellow Hats', 'Abi R', '[{"day":"Sat","start":"15:00","end":"16:00","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 10),
  ('Green Hats', 'Tierna K', '[{"day":"Sat","start":"15:00","end":"16:00","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 11),
  ('Masters', 'Jack P', '[{"day":"Mon","start":"20:30","end":"21:30","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Wed","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"},{"day":"Fri","start":"05:30","end":"07:00","loc":"BSV Long Course","type":"pool"},{"day":"Fri","start":"20:00","end":"21:00","loc":"BSV Short Course – Deep End","type":"pool"}]'::jsonb, 12);

insert into public.volunteer_roles (title, commitment, training, blurb, sort_order) values
  ('Timekeeper', '~2 galas per season', '30-min poolside briefing', 'The classic first step. Sit poolside with a stopwatch, time your lane, enjoy the best seats in the house. No experience needed — we''ll show you everything before the first race.', 0),
  ('Licensed Official (Judge Level 1+)', 'A few meets per year', 'Free Swim England course + mentored poolside hours', 'Progress from Timekeeper to Judge, Starter and beyond. The club funds your training, and every licensed meet we enter needs us to supply officials — you make racing possible.', 1),
  ('Team Manager', 'League rounds & selected meets', 'Swim England Team Manager modules (funded)', 'Look after our swimmers on poolside at away galas — registration, marshalling, and keeping the team fed, warm and where they need to be.', 2),
  ('Meet Helpers (home galas)', 'Ad-hoc — sign-up sheets per event', 'None needed', 'Home meets need runners, refreshments, spectator desk and set-up/pack-down crews. Great for family members who want to help without a regular commitment.', 3),
  ('Committee & Welfare', 'Monthly meeting + role duties', 'Role handover + Wavepower training for welfare', 'Treasurer, secretary, membership, welfare officer — the roles that keep the club running and safe. Talk to any committee member if you''re curious.', 4);

insert into public.news_defaults (key, label, icon, bg, img) values
  ('racing', 'Racing', '🏆', 'linear-gradient(135deg,#d4551a,#101014)', null),
  ('club', 'Club', '🏊', 'linear-gradient(135deg,#f26b21,#ffb25e)', null),
  ('volunteering', 'Volunteering', '🤝', 'linear-gradient(135deg,#101014,#3c3c46)', null),
  ('trips', 'Trips & camps', '✈️', 'linear-gradient(135deg,#1a6fd4,#5eb6ff)', null),
  ('social', 'Social', '🎉', 'linear-gradient(135deg,#7a1ad4,#c15eff)', null),
  ('general', 'General', '📣', 'linear-gradient(135deg,#3c3c46,#101014)', null);
